version: '3'

services:
  fedimintd_1:
    image: fedimint/fedimintd:master
    environment:
      - FM_DATA_DIR=/home/gary-fedimint/fedimint_config
      - FM_BIND_P2P=127.0.0.1:18173
      - FM_P2P_URL=fedimint://10.5.0.5:18173 
      - FM_BIND_API=127.0.0.1:18174
      - FM_API_URL=ws://10.5.0.5:18174
      - FM_BITCOIN_RPC_URL=http://bitcoin:bitcoin@10.5.0.9:43782
      - FM_BITCOIN_RPC_KIND=bitcoind
      - FM_PASSWORD=bitcoin
    ports:
     - "18173:18173"
     - "18174:18174"
    networks:
      app_network:
        ipv4_address: 10.5.0.5

  # gatewayd_1:
  #   image: fedimint/gatewayd:master
  #   networks:
  #     app_network:
  #       ipv4_address: 10.5.0.6

  fedimintd_2:
    image: fedimint/fedimintd:master
    environment:
      - FM_DATA_DIR=/home/gary-fedimint/fedimint_config
      - FM_BIND_P2P=127.0.0.1:18173
      - FM_P2P_URL=fedimint://10.5.0.7:18173 
      - FM_BIND_API=127.0.0.1:18174
      - FM_API_URL=ws://10.5.0.7:18174
      - FM_BITCOIN_RPC_URL=http://bitcoin:bitcoin@10.5.0.9:43782
      - FM_BITCOIN_RPC_KIND=bitcoind
      - FM_PASSWORD=bitcoin
    ports:
     - "18183:18173"
     - "18184:18174"
    networks:
      app_network:
        ipv4_address: 10.5.0.7

  # gatewayd_2:
  #   image: fedimint/gatewayd:master
  #   networks:
  #     app_network:
  #       ipv4_address: 10.5.0.8

  bitcoind:
    restart: always
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:0.18.0-1
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        port=39388
        whitelist=0.0.0.0/0
        rpcauth=bitcoin:bitcoin
    expose:
    - "43782"
    - "39388"
    ports:
      - "43782:43782"
      - "39388:39388"
    volumes:
    - "bitcoin_datadir:/data"
    networks:
      app_network:
        ipv4_address: 10.5.0.9

networks:
  app_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

volumes:
  bitcoin_datadir: